FROM node:18 AS build

WORKDIR /client

COPY /public/ /client/public
COPY /src/ /client/src
COPY /package.json /client/
COPY /tailwind.config.js /client/

RUN npm install

RUN npx tailwindcss -i /client/src/App.css -o /client/src/Tailwind.css
CMD ["npm", "start"]