FROM node:18 AS build

WORKDIR /app

COPY public/ /app/public
COPY src/ /app/src
COPY package.json /app/

RUN npm install

RUN npx tailwindcss -i ./src/App.css -o ./src/Tailwind.css
CMD ["npm", "start"]