version: '3.4'

services:
  projects:
    build:
      context: ./server/CRM_hack
      dockerfile:  /projects/Dockerfile
    ports:
      - "8082:8082"
    restart: always
#    environment:
#      - JAVA_OPTS=-Xms512m -Xmx1024m
  client: 
    build: 
      dockerfile: dockerfile
      context: ./client
    container_name: reactClient
    ports:
      - "3000:3000"
    restart: always
