version: '3.4'

services:
  projects:
    build:
      dockerfile:  ./server/CRM_hack/projects/Dockerfile
    ports:
      - "8082:8082"
    restart: always
#    environment:
#      - JAVA_OPTS=-Xms512m -Xmx1024m
  integrations:
    build:
      dockerfile:  ./server/CRM_hack/inegrations/Dockerfile
    ports:
      - "8083:8083"
    restart: always
#    environment:
#      - JAVA_OPTS=-Xms512m -Xmx1024m
  client: 
    build: 
      dockerfile: dockerfile
      context: ./client
    container_name: reactClient
    ports:
      - "8081:3000"
    restart: always
